import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Wave from 'react-wavify'

const Home: NextPage = () => {
    return (
        <div className="h-full">
            <Head>
                <title>Homepage | Niklas</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/img/favicon.png"/>
            </Head>

            <main className="h-full flex">
                <div className="h-full w-1/2 hidden 2xl:flex relative">
                    <img src="/img/logo-380.png" width={200} height={200} className="absolute z-10 logo"/>
                    <Wave
                        className="rotate-90"
                        fill="url(#gradient)"
                        gradientTransform="rotate(90)"
                        paused={false}
                        options={{
                            height: 20,
                            amplitude: 20,
                            speed: 0.15,
                            points: 3
                        }}
                    >
                        <defs>
                            <linearGradient id="gradient">
                                <stop offset="-100%"  stopColor="#FF50ED" />
                                <stop offset="150%" stopColor="#FFAF37" />
                            </linearGradient>
                        </defs>
                    </Wave>
                </div>
                <div className="h-full flex grow justify-center items-center">
                    <div className="w-full max-w-xl">
                        <div className="pb-10 text-center">
                            <h1 className="text-white text-5xl mb-1">Kontakt</h1>
                            <small className="text-gray-300">
                                Vorübergehend deaktiviert.
                            </small>
                        </div>
                        <form className="flex flex-col px-5">
                            <div className="form-group">
                                <input type="text" className="form-control" placeholder="Name" disabled/>
                            </div>
                            <div className="form-group">
                                <input type="text" className="form-control" placeholder="Email" disabled/>
                            </div>
                            <div className="form-group">
                                <textarea placeholder="Nachricht" rows={8} className="form-control resize-none" disabled/>
                            </div>
                            <div className="flex justify-end">
                                <button className="btn btn-primary" disabled>Senden</button>
                            </div>
                        </form>
                    </div>
                </div>
            </main>
        </div>
    )
}

export default Home
